### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by gl328518397** [jcantosz/netflixConductor-Docker#1]
![conductor-err1](https://cloud.githubusercontent.com/assets/14244945/22615415/602f2238-eacf-11e6-9bef-604a8a6ecd15.png)

--
"Error: Internal Server Error<br> &nbsp; &nbsp;at Request.callback (/netflix/conductor/ui/node_modules/superagent/lib/node/index.js:698:17)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/netflix/conductor/ui/node_modules/superagent/lib/node/index.js:922:12)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)\n"

**Comment by jcantosz** [comment]
Hey @gl328518397: The Netflix/conductor repository now code to generate docker images: [docker folder](https://github.com/Netflix/conductor/tree/dev/docker)

I have updated my comment on the thread: [Issue 14](https://github.com/Netflix/conductor/issues/14) to reflect this.

If you wish to run a singular docker like this test-harness code does (In memory DB - no persistence), the [serverAndUI ](https://github.com/Netflix/conductor/tree/dev/docker/serverAndUI) folder's instructions should be followed. Otherwise please use the [docker-compose.yaml](https://github.com/Netflix/conductor/blob/dev/docker/docker-compose.yaml)

**With regard to the 500 Error:** I believe this has been resolved on the main repository. I cannot find the issue that tracked it, but if I do, I will pass that along.

If you have any further questions on this topic, let me know.

**Comment by gl328518397** [comment]
Thank you ,I will try。
